cops_labels = ['COMMAND_LANGUAGE'] + ['COMPILABLE_PROGRAM'] + ['COMPILER'] + ['COMPILING_A_PROGRAM'] + ['DATA_DESCRIPTION'] + \
              ['DATA_MANIPULATION'] + ['DOMAIN_SPECIFIC_COMPUTER_LANGUAGE'] + ['EXECUTABLE_PROGRAM'] + ['EXECUTING_A_PROGRAM'] +\
              ['GENERAL_IMAGE_FORMAT'] + ['GRID_MIDDLEWARE'] + ['HIGH_LEVEL'] + ['INTERMEDIATE_LANGUAGE'] +\
              ['INTERPRETABLE-PROGRAM'] + ['INTERPRETER'] + ['INTERPRETING_A_PROGRAM'] + ['LIBRARY'] + ['LOW_LEVEL'] +\
              ['MACHINE_LANGUAGE'] + ['MARKUP_LANGUAGE'] + ['MIDDLEWARE'] + ['OPERATING_SYSTEM'] + ['PROGRAM'] + ['QUERY_LANGUAGE'] +\
              ['RUNNING_A_PROGRAM'] + ['RUNNING_A_SOFTWARE'] + ['SOFTWARE'] + ['VIRTUAL_MACHINE']
